"""migrate

Revision ID: e5db3d39bfc8
Revises: 
Create Date: 2025-11-24 22:05:10.011058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5db3d39bfc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('profile_description', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('caregiver',
    sa.Column('caregiver_user_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('caregiving_type', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('caregiver_user_id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('member_user_id', sa.Integer(), nullable=True),
    sa.Column('required_caregiving_type', sa.String(), nullable=True),
    sa.Column('other_requirements', sa.String(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('member',
    sa.Column('member_user_id', sa.Integer(), nullable=False),
    sa.Column('house_rules', sa.String(), nullable=True),
    sa.Column('dependent_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_user_id'], ['USER.user_id'], ),
    sa.PrimaryKeyConstraint('member_user_id')
    )
    op.create_table('address',
    sa.Column('member_user_id', sa.Integer(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('town', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_user_id'], ['member.member_user_id'], ),
    sa.PrimaryKeyConstraint('member_user_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_user_id', sa.Integer(), nullable=True),
    sa.Column('member_user_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('work_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['caregiver.caregiver_user_id'], ),
    sa.ForeignKeyConstraint(['member_user_id'], ['member.member_user_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('job_application',
    sa.Column('caregiver_user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_user_id'], ['caregiver.caregiver_user_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('caregiver_user_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application')
    op.drop_table('appointment')
    op.drop_table('address')
    op.drop_table('member')
    op.drop_table('job')
    op.drop_table('caregiver')
    op.drop_table('USER')
    # ### end Alembic commands ###
